permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
markdown: rdiscount

title: stoutpirate
tagline: sailing the dark nets.. bringing home the goods

author :
  name : Sir Fijimunkii
  email : fijimunkii@gmail.com
  github : fijimunkii
  twitter : fijimunkii

production_url : http://fijimunkii.github.io