permalink: /:title 
auto: true
pygments: true
markdown: rdiscount

title: stoutpirate
tagline: sailing the dark nets.. bringing home the goods

author :
  name : Sir Fijimunkii
  email : fijimunkii@gmail.com
  github : fijimunkii
  twitter : fijimunkii

url : http://fijimunkii.github.io
sitemap: sitemap.xml