auto: true
pygments: true
markdown: rdiscount

title: stoutpirate
tagline: sail the dark nets.. bring home the goods

author :
  name : Sir Fijimunkii
  email : fijimunkii@gmail.com
  github : fijimunkii
  twitter : fijimunkii

url : fijimunkii.github.io
sitemap: sitemap.xml